### ISSUE TITLE
Consider renaming repo name

### ISSUE THREAD

**Issue by FrozenDroid** [nrf-rs/nrf52-hal#113]
Currently there's nrf52 and nrf9160 crates in this repo, I think it'd be better if that was split up, or if the repo name reflected the contents of the repo. Maybe a generic "nrf-hal"?

**Comment by Yatekii** [comment]
Thanks for raising the issue.
We are already aware and discussing internally to find the best solution.
Hopefully we can resolve this soon.

**Comment by jonas-schievink** [comment]
We should try merging the nrf51-hal into this repo too, then naming it nrf5x-hal would be perfect. I'll also merge the nrf5340-hal soon.

**Comment by thejpster** [comment]
> 
> 
> We should try merging the nrf51-hal into this repo too, then naming it nrf5x-hal would be perfect. I'll also merge the nrf5340-hal soon.

*cough* 9160 *cough*

**Comment by jonas-schievink** [comment]
Err, yeah. https://github.com/nrf-rs/nrf52-hal/issues/125 proposes `nrf-hal`, I guess that's fine too.

**Comment by Yatekii** [comment]
Yeah, I think we also discussed somewhere that we might leave the nrf51 support out of the general nrf-hal we are trying to create. Since it's a only thumv6 etc. But since there is now a thumbv8 one in the nrf53, I am not sure about that anymore. How close are the peripherals of the nRF51 and the nRF52?

**Comment by jonas-schievink** [comment]
Some are pretty close (`TEMP`, `RADIO`), but other aren't. I haven't yet looked deeply into this though.

**Comment by Yatekii** [comment]
I think the key point is that we don't sacrifice useability (many cfg flags or suboptimal API for some chips, etc.) just to merge them all, whatever it takes ;)
