### ISSUE TITLE
`SaadcConfig` can only be default-constructed

### ISSUE THREAD

**Issue by jonas-schievink** [nrf-rs/nrf52-hal#119]
It does not have any way of changing its fields, and the only way to create an instance is via `Default::default()`, so all the `Resolution`, `Oversample`, ... settings are impossible to use, unless I'm missing something.

**Comment by jonathanpallant** [comment]
I think this was fixed in https://github.com/nrf-rs/nrf52-hal/pull/114?

**Comment by jonas-schievink** [comment]
Ah, indeed. I ignored that PR because the message suggested it only applied to the nRF9160
