### ISSUE TITLE
Rename `nrf52-hal` to `nrf52832-hal`

### ISSUE THREAD

**Issue by hannobraun** [nrf-rs/nrf52-hal#12]
`nrf52-hal` is actually specific to nRF52832, so the current name is highly misleading in this context.

**Comment by wez** [comment]
Yeah, I'd like to see this happen.  Probably easiest to get this done once both of the outstanding pull requests are merged

**Comment by wez** [comment]
Still to do: review crates.io and rename/archive/publish as appropriate

**Comment by jamesmunns** [comment]
Renamed by #32
