### ISSUE TITLE
How do nrf52-hal-common releases work?

### ISSUE THREAD

**Issue by richardanaya** [nrf-rs/nrf52-hal#122]
I notice that with adafruit-nrf52-bluefruit-le board crate, its built of of much newer abstractions around GPIO pins that are only in the unreleased nrf52-hal-common in git. I'm wondering when the next release of nrf52-hal-common will be so that I can build off newer abstractions without having to use a path dependency.

I'm curious if there's a thought process on when things get released?

**Comment by jamesmunns** [comment]
It's pretty much by request. I'm working on a couple things now, Let's plan maybe a week to the next release? I'll open an issue to track this specifically.

**Comment by richardanaya** [comment]
Awesome! Thank you :)
