### ISSUE TITLE
Consider transitioning peripheral access crates to this organization

### ISSUE THREAD

**Issue by hannobraun** [nrf-rs/nrf52-hal#14]
There are two peripheral access crates that the crates in this repository depend on, but that are not currently living under this organization [nrf52](https://crates.io/crates/nrf52) and [nrf52840](https://crates.io/crates/nrf52840). Would the authors consider transitioning those crates to the nrf-rs organization?

If we do transition those repositories, nrf52 should be renamed to nrf52832.

cc @jamesmunns, @wez, @jscarrott

**Comment by hannobraun** [comment]
If we decide to move these crates here, we should also consider merging them into one repository, as they can likely share build infrastructure (like that Bash script I made for nrf52) between them.

Prior art: https://github.com/adamgreig/stm32-rs

**Comment by jamesmunns** [comment]
For now, I have moved the peripheral access crate to this organization. I will also rename it as @hannobraun suggested above.

Also :+1: from me for merging them as a separate task.

**Comment by jamesmunns** [comment]
Blocked, as I cannot rename items as I don't have admin permissions for repos in this orga yet. CC @wez

**Comment by jscarrott** [comment]
I can do that

**Comment by hannobraun** [comment]
Awesome!
