### ISSUE TITLE
Allow larger SPI buffer sizes on nrf52840 in nrf52-hal-common

### ISSUE THREAD

**Issue by wez** [nrf-rs/nrf52-hal#17]
the `maxcnt` register in the SPI hardware is 8 bits wide on the nrf52382 but wider on the 52840.  The boundary checking code currently constrains the maximum buffer size to 8 bit values which is safe but arbitrarily limiting on the 52840.

Come up with a reasonable way to express this range check that allows taking maximum advantage for the different target devices.

**Comment by jamesmunns** [comment]
Would it make sense to have some kind of `target` module that collects all these details? This would make it easier to conditionally compile. In that target module, we could define constants. Then in the driver, we could do something like:

```rust
#[cfg(target = "nrf52832")]
mod target {
    mod spi {
        pub const MAX_BYTE_COUNT: usize = 255;
    }
}

#[cfg(target = "nrf52840")]
mod target {
    mod spi {
        pub const MAX_BYTE_COUNT: usize = 65535; // made up number
    }
}

// ...

use target::spi::MAX_BYTE_COUNT;

for _ in 0..MAX_BYTE_COUNT { }
```
