### ISSUE TITLE
Whereabouts of the BPROT register on the nRF52840 should be investigated.

### ISSUE THREAD

**Issue by Yatekii** [nrf-rs/nrf52-hal#51]
As per @jamesmunns wishes in https://github.com/nrf-rs/nrf52-hal/diffs/4_ this issue should track the open questions about the missing BPROT register on the nRF52840. For now it's just not accessible through the nRF52840-DK BSP as it's apparently also missing in the pac.

We need to find out:
- Is it really missing?
- Is there an equivalent?
- Has it completely been removed?

edit: and ofc the given link by GH does not work. Dunno how to reference the location before the merge. Will relink once it's merged.

**Comment by ilya-epifanov** [comment]
nRF52840 has an ACL peripheral instead

**Comment by Yatekii** [comment]
Thanks a lot for clearing that up so quick!
