### ISSUE TITLE
Add resources for the two nrf52 chips to the README/repo

### ISSUE THREAD

**Issue by Yatekii** [nrf-rs/nrf52-hal#54]
I think it would be useful to add resources such as reference manuals to the repo.

Question is if it should be links to the PDFs in the README or even included PDFs in the repo that are omitted in a cargo publish.
I would really welcome that as google et. al always show prelim. versions as first hits, potentially fooling users (e.g the 52840er chip had 255byte wide EDMA transfer buffers for 2/3 peripherals when in fact it really has 2^16 - 1 bytes wide transfer buffers for all peripherals (at least at release (v1.0))).

Adding just a link keeps the storage footprint of the repo low and doesn't clutter it so much, where as committing the actual file would prevent broken links in case nordic moving stuff (which they seem to do some time; didn't happen for the reference manual yet tho; afaik).

What do y'all think about this?

Including [0, 1] would up the repo size about 15 Megs.

[2] http://infocenter.nordicsemi.com/pdf/nRF52840_PS_v1.0.pdf
[1] http://infocenter.nordicsemi.com/pdf/nRF52832_PS_v1.4.pdf

**Comment by jamesmunns** [comment]
The 52832 is on PS 1.4 last I checked, btw

**Comment by Yatekii** [comment]
Oh! Well that confirms my point :P

**Comment by jamesmunns** [comment]
@Yatekii would you be interested in adding a table in the README for now linking to where these are officially linked? I'd say if we start running into breakage, we can decide to switch over, but I'd prefer not to check in binary items for now.

**Comment by Yatekii** [comment]
Ok, will do!
