### ISSUE TITLE
SPIM configuration?

### ISSUE THREAD

**Issue by chocol4te** [nrf-rs/nrf52-hal#63]
The current SPIM implementation hardcodes the frequency, mode and over-read character, is this for hardware reasons, or could I work on a PR that makes it configurable (same API as in https://docs.rs/stm32f1xx-hal/0.2.0/stm32f1xx_hal/spi/struct.Spi.html)?

**Comment by jamesmunns** [comment]
@chocol4te I would love a PR that makes this configurable! It is only hardcoded because no one else has implemented a configurable API yet.

The stm32f API you linked looks reasonable.

**Comment by chocol4te** [comment]
Opened a PR: #64
