### ISSUE TITLE
SAADC API?

### ISSUE THREAD

**Issue by chocol4te** [nrf-rs/nrf52-hal#79]
I'm currently trying to get the SAADC working for a project, and thought that adding it to the HAL would be a nice addition. I think I'd start with just a blocking implementation, does anyone have any rough ideas as to how the API should be structured?

**Comment by simonsso** [comment]
If possible try implement the traits from embedded_hal API: https://docs.rs/embedded-hal/0.2.2/embedded_hal/adc/index.html

**Comment by chocol4te** [comment]
🤦‍♀️ I didn’t see that, my bad
