### ISSUE TITLE
Consider renaming gpio::Pin

### ISSUE THREAD

**Issue by jamesmunns** [nrf-rs/nrf52-hal#81]
This name could conflict with [`core::pin::Pin`](https://doc.rust-lang.org/core/pin/struct.Pin.html). We might want to rename it `IOPin`, or `GpioPin`, or similar.

We should decide this before the 0.8.0 release.

**Comment by hannobraun** [comment]
From an API perspective, I think it's fine to leave the name as `Pin`, since you can always use it as `gpio::Pin`. In my opinion that's nicer than `use gpio::GpioPin`.

If we have to use `core::pin::Pin` in `gpio`, that's another problem :-)

**Comment by Yatekii** [comment]
Yeah I also think this is a non-issue for the reasons mentioned tbh. You can always use `pin::Pin` and `gpio::Pin`.
