### ISSUE TITLE
Add nrf52 team as nrf52810-hal owner

### ISSUE THREAD

**Issue by jamesmunns** [nrf-rs/nrf52-hal#91]
CC @hannobraun, could you please add the nrf-rs/nrf52 team as an owner for the nrf52810 crate? Right now you are the only owner.

Edit: On crates.io. You can do this by running the following command from within the crate locally:

```shell
cargo owner --add github:nrf-rs:nrf52
```

**Comment by hannobraun** [comment]
Added the team as owner. Sorry for the oversight.
